services:
  prometheus:
    image: bitnami/prometheus
    volumes:
      - "./prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml:z"
    networks:
      - app_network
    depends_on:
      - app
  app:
    build:
      context: ../
      dockerfile: ./deploy/app/Dockerfile
    restart: always
    ports:
      - $HOST_PORT:8080
    volumes:
      - ./app/config.yaml:/config.yaml
      - ../dev/db/:/db/
    env_file: .env
    networks:
      - app_network
    command: ./app -c ./config.yaml --host $HOST -a app:8080 $APP_FLAGS

networks:
  app_network:
