address: "127.0.0.1" # address app will run on
host: "domain.com" # domain/ip of the server for generating links (if deployed in docker host and address may not match)
# port is configured as APP_PORT env variable

forwarder_config:
  # Create a bot and get the token with https://t.me/BotFather.
  bot_token: "1234567890:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

metrics_config:
  metrics_auth_token: my-secret-metrics-token

repo_config:
  dsn: "./dev/dev.db"