forwarder_config:
  # Create a bot and get the token with https://t.me/BotFather.
  bot_token: "1234567890:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

http_config:
  host: "127.0.0.1"
  port: 1337

metrics_config:
  metrics_auth_token: my-secret-metrics-token