forwarder_config:
  tg_config:
    # Create a bot and get the token with https://t.me/BotFather.
    token: "1234567890:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    # To forward messages to yourself, find your ID with https://t.me/userinfobot.
    # Don't forget to /start a conversation with the bot you created.
    chat_id: 123456789

http_config:
  address: 127.0.0.1
  port: 1337
  confirmationString: "12345"
